name: "Space City"
description: "Looking at future places!!!"
author: "Kevin Nguyen"

url: "http://knguyenknguyen.github.io/space-city/"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
